name: test

on:
  push:
    branches: [ adobe ]
  pull_request:
    branches: [ adobe ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup
      run: make setup

    - name: Test
      run: |
        make build
        make test-race
        make check
        make bench-race
